name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 19
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm run cypress-api
    - name: Report results
      uses: cypress-io/github-action@v2
      with:
        record: true
        parallel: true
        config-file: cypress.config.js
